
package services.server.openlm;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdminAPI", targetNamespace = "OpenLM.Server.Services", wsdlLocation = "http://192.168.0.100:7020/OpenLM.Server.Services/AdminAPI?singleWsdl")
public class AdminAPI
    extends Service
{

    private final static URL ADMINAPI_WSDL_LOCATION;
    private final static WebServiceException ADMINAPI_EXCEPTION;
    private final static QName ADMINAPI_QNAME = new QName("OpenLM.Server.Services", "AdminAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.100:7020/OpenLM.Server.Services/AdminAPI?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINAPI_WSDL_LOCATION = url;
        ADMINAPI_EXCEPTION = e;
    }

    public AdminAPI() {
        super(__getWsdlLocation(), ADMINAPI_QNAME);
    }

    public AdminAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINAPI_QNAME, features);
    }

    public AdminAPI(URL wsdlLocation) {
        super(wsdlLocation, ADMINAPI_QNAME);
    }

    public AdminAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINAPI_QNAME, features);
    }

    public AdminAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAdminAPI
     */
    @WebEndpoint(name = "basicHttpBindingConfiguration_IAdminAPI")
    public IAdminAPI getBasicHttpBindingConfigurationIAdminAPI() {
        return super.getPort(new QName("OpenLM.Server.Services", "basicHttpBindingConfiguration_IAdminAPI"), IAdminAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAdminAPI
     */
    @WebEndpoint(name = "basicHttpBindingConfiguration_IAdminAPI")
    public IAdminAPI getBasicHttpBindingConfigurationIAdminAPI(WebServiceFeature... features) {
        return super.getPort(new QName("OpenLM.Server.Services", "basicHttpBindingConfiguration_IAdminAPI"), IAdminAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINAPI_EXCEPTION!= null) {
            throw ADMINAPI_EXCEPTION;
        }
        return ADMINAPI_WSDL_LOCATION;
    }

}
